<?php
/**
 * Even Fibonacci numbers
 *
 * @description Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 */

function fibonacciEvens($prevNum, $currentNum, $total) {
    $nextNum = $prevNum + $currentNum;
    $total = $total ? $total : 0;

    if($currentNum % 2 == 0) {
        $total += $currentNum;
    }
    if($nextNum <= 4e6) {
        return fibonacciEvens($currentNum, $nextNum, $total);
    }
    return $total;
}

echo fibonacciEvens(1, 2, 0);

?>
